-- ==========================================================================
--  002. LaserFish 데이터를 baekjonghwi's Project(arymzgsayptprrbdnzwd)에서
--       masslabs 프로젝트의 laserfish 스키마로 옮긴다.
--
--  🔴옮길 데이터가 없다 — 원본이 전 테이블 0행이라 구조만 새로 만든다.
--    (2026-08-17 확인. 사용자가 "전부 시험 데이터라 없어져도 된다"고 확인함)
--
--  원본과 달라지는 점 두 가지. 둘 다 데이터가 없어서 지금 바로잡는 게 공짜다.
--   ① id를 전부 `generated by default as identity`로 통일했다.
--      원본은 Slab_1/2/3이 "Slab_id_seq" 하나를 공유했고, Roof만 GENERATED
--      ALWAYS라 id를 직접 넣으면 거부됐다. 통일해 두면 그런 함정이 없다.
--   ② 🔴RLS 정책을 전 테이블에 건다. 원본은 19개 중 9개에만 정책이 있었고
--      나머지 10개는 RLS만 켜져 있어 anon 삽입이 전부 조용히 거부됐다.
--      플러그인이 응답 코드를 안 보기 때문에 아무도 눈치채지 못한 상태였다.
-- ==========================================================================

create schema if not exists laserfish;

-- ── 세션 헤더 ─────────────────────────────────────────────────────────────
create table laserfish."LaserCut" (
  id           bigint generated by default as identity primary key,
  created_at   timestamptz not null default now(),
  country      text,
  session_id   text not null,
  scale        double precision,
  total_count  bigint,
  wall_count   bigint,
  slab_count   bigint,
  stair_count  bigint,
  window_count bigint,
  roof_count   bigint
);

-- ── 직선 벽 1~3 (면 + 커브) ───────────────────────────────────────────────
create table laserfish."LaserCut_Wall_1" (
  id           bigint generated by default as identity primary key,
  session_id   text,
  surface_json text,
  curve_json   text,
  wall_thick   double precision
);
create table laserfish."LaserCut_Wall_2" (like laserfish."LaserCut_Wall_1" including all);
create table laserfish."LaserCut_Wall_3" (like laserfish."LaserCut_Wall_1" including all);

-- ── 직선 벽 4~5 + 창문 (created_at 있는 세대) ─────────────────────────────
create table laserfish."LaserCut_Wall_4" (
  id           bigint generated by default as identity primary key,
  created_at   timestamptz default now(),
  session_id   text,
  wall_thick   double precision,
  surface_json text,
  curve_json   text
);
create table laserfish."LaserCut_Wall_5" (like laserfish."LaserCut_Wall_4" including all);
create table laserfish."LaserCut_Window" (like laserfish."LaserCut_Wall_4" including all);

-- ── 곡선 벽 1~3 (면 + 커브 + 높이) ────────────────────────────────────────
create table laserfish."LaserCut_WallCrv_1" (
  id           bigint generated by default as identity primary key,
  session_id   text,
  surface_json text,
  curve_json   text,
  height_json  text,
  wall_thick   double precision
);
create table laserfish."LaserCut_WallCrv_2" (like laserfish."LaserCut_WallCrv_1" including all);
create table laserfish."LaserCut_WallCrv_3" (like laserfish."LaserCut_WallCrv_1" including all);

-- ── 곡선 벽 4~5 + 창문 ────────────────────────────────────────────────────
create table laserfish."LaserCut_WallCrv_4" (
  id           bigint generated by default as identity primary key,
  created_at   timestamptz default now(),
  session_id   text,
  wall_thick   double precision,
  surface_json text,
  curve_json   text,
  height_json  text
);
create table laserfish."LaserCut_WallCrv_5"      (like laserfish."LaserCut_WallCrv_4" including all);
create table laserfish."LaserCut_WallCrv_Window" (like laserfish."LaserCut_WallCrv_4" including all);

-- ── 슬라브 1~3 + 지붕 (커브만) ────────────────────────────────────────────
create table laserfish."LaserCut_Slab_1" (
  id         bigint generated by default as identity primary key,
  session_id text,
  slab_thick double precision,
  curve_json text
);
create table laserfish."LaserCut_Slab_2" (like laserfish."LaserCut_Slab_1" including all);
create table laserfish."LaserCut_Slab_3" (like laserfish."LaserCut_Slab_1" including all);
create table laserfish."LaserCut_Roof"   (like laserfish."LaserCut_Slab_1" including all);

-- ── 계단 ──────────────────────────────────────────────────────────────────
create table laserfish."LaserCut_Stair" (
  id          bigint generated by default as identity primary key,
  session_id  text,
  stair_thick double precision,
  curve_json  text
);

-- ── 리뷰 ──────────────────────────────────────────────────────────────────
-- 🔴여기는 anon 정책을 일부러 안 건다. /api/submit-review가 service_role로
--   쓰고, 그 전에 포트원으로 결제 여부를 검증한다. anon에 열면 누구나
--   아무 리뷰나 넣을 수 있다.
create table laserfish.reviews (
  id         uuid primary key default gen_random_uuid(),
  payment_id text not null,
  nickname   text not null,
  review     text not null,
  photo_url  text,
  created_at timestamptz not null default now()
);

-- ── RLS ───────────────────────────────────────────────────────────────────
-- 플러그인은 publishable(anon) 키로 쓰기만 한다. 읽기는 열지 않는다 —
-- 남의 도면 데이터를 anon 키로 긁어갈 수 있으면 안 된다(= 쓰기 전용 우편함).
do $$
declare t text;
begin
  for t in
    select tablename from pg_tables where schemaname = 'laserfish'
  loop
    execute format('alter table laserfish.%I enable row level security', t);
    if t <> 'reviews' then
      execute format(
        'create policy "plugin insert" on laserfish.%I for insert to anon, authenticated with check (true)', t);
    end if;
  end loop;
end $$;

grant usage on schema laserfish to anon, authenticated, service_role;
grant all on all tables    in schema laserfish to anon, authenticated, service_role;
grant all on all sequences in schema laserfish to anon, authenticated, service_role;
alter default privileges in schema laserfish grant all on tables    to anon, authenticated, service_role;
alter default privileges in schema laserfish grant all on sequences to anon, authenticated, service_role;

-- ⚠️실행 후 Settings > API > Exposed schemas 에 laserfish 를 추가할 것.
-- ⚠️플러그인은 요청에 Content-Profile: laserfish 헤더를 붙여야 이 스키마에 닿는다.
